### ISSUE TITLE
可以提供一个在 iOS上的 Demo 吗？

### ISSUE THREAD

**Issue by ednew2018** [xxf098/go-tun2socks-build#1]
希望您能提供一个在 iOS 上使用这个项目的 DEMO，以供学习

**Comment by xxf098** [comment]
在Linux上没办法配置iOS开发环境，你可以自己尝试解决，应该比较简单

**Comment by ednew2018** [comment]
谢谢，找到了这个 https://github.com/duanhai/Tun2socks-PacketTunnelDemo
