### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by tormentous** [xxf098/go-tun2socks-build#10]
I try to build using mac with the following command in terminal..

cd /Users/admin/Desktop/go-tun2socks
export GOPATH=$HOME/go
export PATH="$GOPATH/bin:$PATH"
export ANDROID_HOME=/Users/admin/Library/Android/sdk
export ANDROID_NDK_HOME=/Users/admin/adt-bundle-mac-x86_64-20140702/sdk/ndk/21.3.6528147
go get -d
go: v2ray.com/core@v4.19.1+incompatible: parsing v2ray-core/go.mod: open /Users/admin/Desktop/go-tun2socks/v2ray-core/go.mod: no such file or directory

**Comment by tormentous** [comment]
resolved.

**Comment by never-afk** [comment]
how?

> resolved.
