### ISSUE TITLE
兄弟好像又出问题了 

### ISSUE THREAD

**Issue by simo8102** [xxf098/go-tun2socks-build#14]
你在upgrade v4.36.2这个版本之后就出现了没法解析dns了
在update go.sum这个版本得时候还没问题
以前启动都会出现
![git](https://user-images.githubusercontent.com/45913291/111912788-30088100-8aa6-11eb-9c15-ccf7a9fcf56a.png)
现在的版本都不会出现这个了 是不是dns解析模块出了错误

**Comment by rurirei** [comment]
it is not bug. https://github.com/v2fly/v2ray-core/pull/767
