### ISSUE TITLE
关于流量统计问题

### ISSUE THREAD

**Issue by simo8102** [xxf098/go-tun2socks-build#16]
type QuerySpeed interface {
	UpdateTraffic(up int64, down int64)
}

up down 返回的都是 0
不知是我使用错误还是这个方法没法获取统计

**Comment by xxf098** [comment]
https://www.v2ray.com/en/configuration/overview.html#outboundobject

outbound里面的tag设成`proxy`试试

**Comment by simo8102** [comment]
> https://www.v2ray.com/en/configuration/overview.html#outboundobject
> 
> outbound里面的tag设成`proxy`试试

改了好像并没有什么作用
还是全部为0

**Comment by xxf098** [comment]
从v2rayng里导出一个JSON配置

**Comment by simo8102** [comment]
> 从v2rayng里导出一个JSON配置

我在试下
