### ISSUE TITLE
make ios 构建失败

### ISSUE THREAD

**Issue by LeeCenY** [xxf098/go-tun2socks-build#19]
<pre>
$ make ios
</pre>

<pre>
mkdir -p /Users/xxxx/Downloads/go-tun2socks-build/build
eval "cd /Users/xxxx/Downloads/go-tun2socks-build/build && gomobile bind -a -ldflags '-s -w -X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn' -target=ios -o /Users/xxxx/Downloads/go-tun2socks-build/build/Tun2socks.framework github.com/xxf098/go-tun2socks-build"
/bin/sh: gomobile: command not found
make: *** [ios] Error 127
</pre>

<pre>
$ go get golang.org/x/mobile/cmd/gomobile
$ gomobile init
</pre>

<pre>
xxxx@Mac-mini ~ % go get golang.org/x/mobile/cmd/gomobile
xxxx@Mac-mini ~ % gomobile init
zsh: command not found: gomobile

</pre>

<details><summary><code>$ go env</code> Output</summary><br><pre>                     
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xxxx/Library/Caches/go-build"
GOENV="/Users/xxxx/Library/Application Support/go/env"
GOEXE=""
GOFLAGS="-mod=mod"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xxxx/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xxxx/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/Cellar/go@1.16/1.16.14/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go@1.16/1.16.14/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.14"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/xxxx/Downloads/go-tun2socks-build/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tn/jgrzgk7j4mx9szrz97lbnyc00000gn/T/go-build2563246633=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

**Comment by xxf098** [comment]
add Go binary path to your PATH environment variable.
like: export PATH=$PATH:/usr/local/go/bin:~/go/bin

**Comment by LeeCenY** [comment]
Thanks, this command can solve my problem above

<pre>
$ make ios
</pre>

<pre>
gomobile: static framework name "/Users/xxx/Downloads/go-tun2socks-build/build/Tun2socks.framework" missing .xcframework suffix
make: *** [ios] Error 1
</pre>



I changed the Makefile Tun2socks.framework to Tun2socks.xcframework (I'll try to modify it, I don't know if this is correct)

https://github.com/xxf098/go-tun2socks-build/blob/2c091a2956601d03d9bb66fb2d55f9e68f625feb/Makefile#L4


<pre>
$ make ios
</pre>

<pre>

mkdir -p /Users/xxxx/Downloads/go-tun2socks-build/build
eval "cd /Users/xxxx/Downloads/go-tun2socks-build/build && gomobile bind -a -ldflags '-s -w -X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn' -target=ios -o /Users/xxxx/Downloads/go-tun2socks-build/build/Tun2socks.xcframework github.com/xxf098/go-tun2socks-build"
gomobile: /Users/xxxx/go/bin/gobind -lang=go,objc -outdir=/var/folders/gd/mj5d2t3j3p94dh3z21966d500000gn/T/gomobile-work-848457379/ios -tags=ios github.com/xxf098/go-tun2socks-build failed: exit status 1
unsupported, named type github.com/xxf098/go-tun2socks-build.Shadowsocks
unsupported, named type github.com/xxf098/go-tun2socks-build.Shadowsocks
unsupported, named type github.com/xxf098/go-tun2socks-build.Shadowsocks
unsupported, named type github.com/xxf098/go-tun2socks-build.Shadowsocks
unsupported, named type github.com/xxf098/go-tun2socks-build.Shadowsocks
unsupported, named type github.com/xxf098/go-tun2socks-build.Shadowsocks
unsupported, named type github.com/xxf098/go-tun2socks-build.Shadowsocks
unsupported, named type github.com/xxf098/go-tun2socks-build.Shadowsocks
unsupported, named type github.com/xxf098/go-tun2socks-build.Shadowsocks
unsupported, named type github.com/xxf098/go-tun2socks-build.Shadowsocks

make: *** [ios] Error 1
</pre>

<details><summary><code>$ go env</code> Output</summary><br><pre>         
xxxxdeMacBook-Pro go-tun2socks-build % go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xxxx/Library/Caches/go-build"
GOENV="/Users/xxxx/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xxxx/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xxxx/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.6/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/xxxx/Downloads/go-tun2socks-build/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gd/mj5d2t3j3p94dh3z21966d500000gn/T/go-build148632453=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Comment by LeeCenY** [comment]
See that you choose to remove the iOS build. I'm a bit embarrassed.

**Comment by xxf098** [comment]
I'am not an ios developer, sorry for this.

**Comment by 594810899** [comment]
> 看到您选择删除iOS版本。我有点尴尬。


请问一下  你这个iOS的编译成功了没？
