### ISSUE TITLE
go get 失败

### ISSUE THREAD

**Issue by Sopage** [xxf098/go-tun2socks-build#20]
mac os 
go version go1.17.6 darwin/arm64
执行
$: go get -d ./... 
go: github.com/v2fly/v2ray-core/v4@v4.43.0 (replaced by ../v2ray-core): reading ../v2ray-core/go.mod: open /Users/develop/Documents/workspaces/gowork/src/github.com/xxf098/v2ray-core/go.mod: no such file or directory

查看go.mod文件replace处，是否缺少依赖？lite分支

**Comment by xxf098** [comment]
remove these lines to use the default v2ray-core/xray-core lib
```
github.com/v2fly/v2ray-core/v4 v4.43.0 => ../v2ray-core
github.com/xtls/ v1.5.3 => ../xray-core
```
clone this repo `https://github.com/xxf098/LiteSpeedTest` to path `../lite-proxy`

**Comment by Sopage** [comment]
> remove these lines to use the default v2ray-core/xray-core lib
> 
> ```
> github.com/v2fly/v2ray-core/v4 v4.43.0 => ../v2ray-core
> github.com/xtls/ v1.5.3 => ../xray-core
> ```
> 
> clone this repo `https://github.com/xxf098/LiteSpeedTest` to path `../lite-proxy`

**Comment by Sopage** [comment]
作者你好，按你给的方式确实没有在出现上述问题！出现下面的新问题
github.com/xxf098/go-tun2socks-build imports
	github.com/xxf098/go-tun2socks-build/settings: cannot find module providing package github.com/xxf098/go-tun2socks-build/settings
	
目前有个疑问：
作者对v2fly/v2ray-core和xtls/xray-core 在使用的时候有什么改动吗？

目前我有个想法想把wireguard的东西加到这里面想提交个PR

**Comment by xxf098** [comment]
pull the latest code to fix the problem

modify v2ray/xray code for debug

**Comment by Sopage** [comment]
依赖没问题了！这回编译出问题了
go-tun2socks-build/v2ray/hosts.go:36:26: undefined: conf.NewHostAddress
发现
github.com/v2fly/v2ray-core/v4/infra/conf中不存在NewHostAddress
应该是你本地的v2fly/v2ray-core存在，而新v2fly/v2ray-core中被剔除了吧？
![image](https://user-images.githubusercontent.com/2882974/157159051-2549a0ff-f31e-49c9-8f1a-9402038110dd.png)

**Comment by Sopage** [comment]
不愿解决就算了

**Comment by xxf098** [comment]
add this function inside ./v2ray-core/infra/conf/dns.go

func NewHostAddress(addr *cfgcommon.Address) *HostAddress {
	return &HostAddress{addr: addr}
}

**Comment by zeku2022** [comment]
thanks a lot. It's very hard to find a good tun2socks framework...so many fails....
finally your git respo can successfully compile....😂

**Comment by WangLiquan** [comment]
作者你好，现在的包好像还有这个问题，而且我看传参已经变了。现在是不是更换了要修改的文件和方法
