### ISSUE TITLE
Query stats

### ISSUE THREAD

**Issue by napsterphantom** [xxf098/go-tun2socks-build#5]
Hello, what parameters does Tun2socks.querystats() take.
And as a suggestion, how about making a brief documentation for such stuff. By the way, this is so far the best tun2socks implementation with v2ray support

**Comment by xxf098** [comment]
check the source code
https://github.com/v2ray/v2ray-core/blob/master/app/dispatcher/default.go#L157
https://github.com/v2ray/v2ray-core/blob/master/app/dispatcher/default.go#L166

Register a new counter, then query status with that name. There are some built in counters.
To use Tun2socks.querystats(), just change the name to something like below.
```go
name := "user>>>" + user.Email + ">>>traffic>>>downlink"
```

**Comment by napsterphantom** [comment]
Thanks. So, if I want to query the downlink in the current session. Would it be something like,
Tun2socks.querystats(">>>traffic>>>downlink")

**Comment by xxf098** [comment]
Go
```go
func QueryStats(direct string) int64 {
	if statsManager == nil {
		return 0
	}
	name := name := "user>>>xxf098@github.com>>traffic>>>" + direct
	counter := statsManager.GetCounter(name)
	if counter == nil {
		return 0
	}
	return counter.Set(0)
}
```
Java
```java
Tun2socks.querystats("downlink");
Tun2socks.querystats("uplink");
```

**Comment by napsterphantom** [comment]
Thanks.

**Comment by napsterphantom** [comment]
Hlo, I decided to revisit this project, tried your solution, however the method still turns 0 bytes everytime it is called. What i did, i changed the querystats method and modified the counter to this

func  QueryStats(tag string, direct string) int64 {
	if v.statsManager == nil {
		return 0
	}
	counter := v.statsManager.GetCounter(fmt.Sprintf("inbound>>>%s>>>traffic>>>%s", tag, direct))
	if counter == nil {
		return 0
	}
	return counter.Set(0)
}


My v2ray configuration is something like this, ofcourse this is a stub

{
  "stats":{},
  "log": {
    "loglevel": "warning"
  },
  "policy":{
    "levels": {
      "8": {
        "handshake": 4,
        "connIdle": 300,
        "uplinkOnly": 1,
        "downlinkOnly": 1
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  },
  "inbounds": [{
    "tag": "socks-in",
    "port": 10808,
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "userLevel": 8
    },
    "sniffing": {
      "enabled": true,
      "destOverride": [
        "http",
        "tls"
      ]
    }
  },
    {
      "tag": "http",
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      }
    }
  ],
  "outbounds": [{
    "tag": "proxy",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "v2ray.cool",
          "port": 10086,
          "users": [
            {
              "id": "a3482e88-686a-4a58-8126-99c9df64b7bf",
              "alterId": 64,
              "security": "auto",
              "level": 8
            }
          ]
        }
      ],
      "servers": [
        {
          "address": "v2ray.cool",
          "method": "chacha20",
          "ota": false,
          "password": "123456",
          "port": 10086,
          "level": 8
        }
      ]
    },
    "streamSettings": {
      "network": "tcp"
    },
    "mux": {
      "enabled": false
    }
  },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "block",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "routing": {
    "domainStrategy": "Asls",
    "rules": []
  },
  "dns": {
    "hosts": {},
    "servers": []
  }
}

I then in my java code call Tun2socks.querystats("socks","uplink") and Tun2socks.querystats("socks","downlink"), this however continuosly still returns 0 bytes everytime.

However, i switched to https://github.com/2dust/v2rayNG/tree/master/AndroidLibV2rayLite 
and the same counter returns the desired results.
What could the problem be now? Thanks.

**Comment by xxf098** [comment]
The query strategies are different. 

v2rayng
https://github.com/v2ray/v2ray-core/blob/master/app/proxyman/inbound/always.go#L26

This Project
https://github.com/v2ray/v2ray-core/blob/master/app/dispatcher/default.go#L157
you need to add a user email to get the stats
```json
    "users":[
        {
            "id":"a3482e88-686a-4a58-8126-99c9df64b7bf",
            "alterId":64,
            "security":"auto",
            "level":8,
            "email":"xxf098@github.com"
        }
    ]

```

**Comment by napsterphantom** [comment]
Wow, thanks for that. It did the job, would love to send you a playstore link of my app that uses your library if you don't mind 😊

**Comment by xxf098** [comment]
send to this email: ufxmeng#gmail.com

**Comment by napsterphantom** [comment]
OK... I guess let me close this too
