### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by titanniubility** [xxf098/go-tun2socks-build#7]
![image](https://user-images.githubusercontent.com/35965537/87239554-08571880-c443-11ea-93c6-06af5966cef3.png)
please view, thank youe

**Comment by xxf098** [comment]
https://github.com/grpc/grpc-go#compiling-error-undefined-grpcsupportpackageisversion
After upgraded v2ray-core, You need to update related dependencies.

**Comment by wheatj** [comment]
hello xxf098, i am titanniubility, if i don't want to update related dependencies(because i think it's a little trouble, i need to use what's version of v2ray-core in direct.
thank you.

**Comment by xxf098** [comment]
checkout this commit https://github.com/v2ray/v2ray-core/commit/09b81b78c3a0c4afbc523fc371ea6b1bdde9d679
you may use v4.23.4

**Comment by titanniubility** [comment]
hello, xxf098:
i read your source of "go-tun2socks-build " and eycorsican's go-tun2socks,
all they have "vsession.DefaultDBService = dbService" code, but I can't
found it in v2ray'source, can you tell me what 's version have it.
thank you very much

xxf098 <notifications@github.com> 于2020年7月12日周日 下午2:31写道：

**Comment by xxf098** [comment]
DefaultDBService is a custom API by eycorsican, which is not existed in the official v2ray-core release.
